server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contact?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: kynd7678
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000